### ISSUE TITLE
Lockdown is somewhat outdated

### ISSUE THREAD

**Issue by csuhta** [ernw/hardening#1] opened 2016-08-23 18:29 UTC
Minor note, but Lockdown.app has many false-postive/negatives on OS X 10.11.6. It doesn't seem to be updated for El Capitan.

Here are two examples of confusing results for an audit:

![jb7iuj04](https://cloud.githubusercontent.com/assets/769083/17904573/dd8d1064-693d-11e6-9675-f3364e9ade6f.png)
![v9jyd8g4](https://cloud.githubusercontent.com/assets/769083/17904575/de776a10-693d-11e6-8c95-09871a5f8a17.png)

**Comment by Traxes** [comment] 2016-08-25 12:20
sometimes the confusing thing is true. simply because it´s the other way around. 
for example the second Screenshot checks if the automatic Time and Date setting is off. if not it will display failed. Which would be correct in this scenario.

Input: `sudo systemsetup getusingnetworktime`
Output: `Network Time: On`

But i couldn´t reproduce the first issue:
Input: `Traxes$ defaults read com.apple.screensaver askForPassword | grep 1`
Output: `1`

btw: this is how it works in the background (Yaml config):

`- title: "Disable automatic setting of time and date"`
  `check_command: | sudo systemsetup getusingnetworktime | grep 'Network Time: Off'`
  `fix_command: |sudo systemsetup setusingnetworktime off`
  `enabled: true`

you can adjust and add your own settings there.

To lookup what command for each setting is exactly executed and checked: [https://github.com/SummitRoute/osxlockdown](https://github.com/SummitRoute/osxlockdown/blob/master/commands.yaml):

Cheers, 
Traxes

**Comment by takeshixx** [comment] 2017-10-09 11:05
Feel free to close the issue if it has been resolved, thanks.

**Comment by Traxes** [comment] 2018-01-09 08:21
Closed the issue due to inactivity.

**Closed as completed by Traxes** 2018-01-09 08:21 UTC
